version: '3'

silent: true

includes:
  db:
    taskfile: .task/Taskfile.db.yaml

  docker:
    taskfile: .task/Taskfile.docker.yaml

tasks:
  default:
    # desc: Show commands
    cmds:
      - task -l --sort none
