spring:
  application:
    name: server
  main:
    banner-mode: off
  graphql:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
    graphiql:
      enabled: true
  r2dbc:
    url: ${R2DBC_URL}
