name: Server
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['server/**']
  pull_request:
    paths: ['server/**']

defaults:
  run:
    shell: bash
    working-directory: ./server

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: Asia/Tokyo
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            db
            server
            .env.example
            .envrc

      - name: Setup environment file at root
        working-directory: .
        run: cp .env.example .env

      - name: Setup environment file at server
        run: cp .env.example .env

      - name: Restore direnv cache
        id: cache-direnv
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /opt/pipx_bin/direnv
          key: ${{ runner.os }}-direnv-cache

      - name: Install direnv if not cached
        if: steps.cache-direnv.outputs.cache-hit != 'true'
        run: |
          curl -sfL https://direnv.net/install.sh | bash

      - name: Save direnv cache
        if: steps.cache-direnv.outputs.cache-hit != 'true'
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /opt/pipx_bin/direnv
          key: ${{ runner.os }}-direnv-cache

      - name: Allow .envrc
        run: direnv allow

      - name: Load PATH changes
        run: direnv exec . sh -c 'echo $PATH' > "$GITHUB_PATH"

      - name: Load other environment changes
        run: direnv export gha >> "$GITHUB_ENV"

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 21.0.4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Gradle reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: Gradle reports
          path: ./server/build/reports
