name: Web
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['web/**']
  pull_request:
    paths: ['web/**']

defaults:
  run:
    shell: bash
    working-directory: ./web

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout sources
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          sparse-checkout: |
            web
            server

      - name: Setup environment file at web
        run: cp .env.example .env

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          package_json_file: ./web/package.json

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: ./web/.node-version
          cache: 'pnpm'
          cache-dependency-path: ./web/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Check lint and format
        run: pnpm check

      - name: Run build
        run: pnpm build
